# This is the config.yaml for generating the 3D Model Viewer website.
# pages:
#   page_name:
#     ModelSrcPath: "/example/obj.glb"
#     ModelIosSrcPath: "/example/obj.usdz"
#     PosterPath: "/example/obj.webp"
#     Description: "About_Me"
#     ModelName: "Your_Model_Name"
#     DesignerWebsite: "Your_Website"
#     DesignerName: "Your_Name"

Pages:
  page1:
    ModelSrcPath: "/static/models/obj1/object1.glb"
    ModelIosSrcPath: "/static/models/obj1/object1.usdz"
    PosterPath: "/static/models/obj1/object1.webp"
    Description: "This is my masterpiece"
    ModelName: "Object 1"
    DesignerWebsite: "https://lemorage.github.io/"
    DesignerName: "Lemorage"
